/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JTranspose */

#ifndef _Included_com_wsr_cpu_JTranspose
#define _Included_com_wsr_cpu_JTranspose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD2
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD2
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD3
 * Signature: (Ljava/nio/ByteBuffer;IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD4
 * Signature: (Ljava/nio/ByteBuffer;IIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
