/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JMatMul */

#ifndef _Included_com_wsr_cpu_JMatMul
#define _Included_com_wsr_cpu_JMatMul
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JMatMul
 * Method:    inner
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMatMul_inner
  (JNIEnv *, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JMatMul
 * Method:    matMulD1ToD2
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ZIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMatMul_matMulD1ToD2
  (JNIEnv *, jobject, jobject, jobject, jboolean, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JMatMul
 * Method:    matMulD2ToD1
 * Signature: (Ljava/nio/ByteBuffer;ZLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMatMul_matMulD2ToD1
  (JNIEnv *, jobject, jobject, jboolean, jobject, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JMatMul
 * Method:    matMulD2ToD2
 * Signature: (Ljava/nio/ByteBuffer;ZLjava/nio/ByteBuffer;ZIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMatMul_matMulD2ToD2
  (JNIEnv *, jobject, jobject, jboolean, jobject, jboolean, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
