/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_gpu_JCLBlast */

#ifndef _Included_com_wsr_gpu_JCLBlast
#define _Included_com_wsr_gpu_JCLBlast
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_gpu_JCLBlast
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wsr_gpu_JCLBlast_init
  (JNIEnv *, jobject);

/*
 * Class:     com_wsr_gpu_JCLBlast
 * Method:    transfer
 * Signature: ([FI)J
 */
JNIEXPORT jlong JNICALL Java_com_wsr_gpu_JCLBlast_transfer
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_wsr_gpu_JCLBlast
 * Method:    read
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_wsr_gpu_JCLBlast_read
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_wsr_gpu_JCLBlast
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wsr_gpu_JCLBlast_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wsr_gpu_JCLBlast
 * Method:    sgemm
 * Signature: (ZZIIIFJIJIFJII)V
 */
JNIEXPORT void JNICALL Java_com_wsr_gpu_JCLBlast_sgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jfloat, jlong, jint, jlong, jint, jfloat, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
