[versions]
# Library Info
lib-group-id = "com.github.Wansuko-cmd"
lib-version = "0.0.32-alpha05"

# kotlin
kotlin = "2.4.10"

# ksp
ksp = "2.3.10"

# serialization
serialization = "1.11.0"

# coroutines
coroutines = "1.10.1"

# okio
okio = "3.17.0"

# Ktlint
ktlint = "14.2.0"
ktlint-lib = "1.8.0"

# Android
agp = "9.2.1"
android-compile-sdk = "36"
android-min-sdk = "33"

[libraries]
# ksp
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# serialization
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization" }
serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }

# coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
