/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cl_JCLBlast */

#ifndef _Included_com_wsr_cl_JCLBlast
#define _Included_com_wsr_cl_JCLBlast
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_init
  (JNIEnv *, jobject);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    transfer
 * Signature: ([FI)J
 */
JNIEXPORT jlong JNICALL Java_com_wsr_cl_JCLBlast_transfer
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    read
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_read
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sdot
 * Signature: (IJIJI)F
 */
JNIEXPORT jfloat JNICALL Java_com_wsr_cl_JCLBlast_sdot
  (JNIEnv *, jobject, jint, jlong, jint, jlong, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sscal
 * Signature: (IFJI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sscal
  (JNIEnv *, jobject, jint, jfloat, jlong, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    saxpy
 * Signature: (IFJIJI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_saxpy
  (JNIEnv *, jobject, jint, jfloat, jlong, jint, jlong, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sgemm
 * Signature: (ZZIIIFJIJIFJII)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jfloat, jlong, jint, jlong, jint, jfloat, jlong, jint, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sgemv
 * Signature: (ZIIFJIJIFJI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sgemv
  (JNIEnv *, jobject, jboolean, jint, jint, jfloat, jlong, jint, jlong, jint, jfloat, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
