/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_JBLAS */

#ifndef _Included_com_wsr_JBLAS
#define _Included_com_wsr_JBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_JBLAS
 * Method:    ddot
 * Signature: (I[DI[DI)D
 */
JNIEXPORT jFloat JNICALL Java_com_wsr_JBLAS_ddot
  (JNIEnv *, jobject, jint, jFloatArray, jint, jFloatArray, jint);

/*
 * Class:     com_wsr_JBLAS
 * Method:    dscal
 * Signature: (ID[DI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_JBLAS_dscal
  (JNIEnv *, jobject, jint, jFloat, jFloatArray, jint);

/*
 * Class:     com_wsr_JBLAS
 * Method:    daxpy
 * Signature: (ID[DI[DI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_JBLAS_daxpy
  (JNIEnv *, jobject, jint, jFloat, jFloatArray, jint, jFloatArray, jint);

/*
 * Class:     com_wsr_JBLAS
 * Method:    dgemm
 * Signature: (ZZIIID[DI[DID[DI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_JBLAS_dgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jFloat, jFloatArray, jint, jFloatArray, jint, jFloat, jFloatArray, jint);

/*
 * Class:     com_wsr_JBLAS
 * Method:    dgemv
 * Signature: (ZIID[DI[DID[DI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_JBLAS_dgemv
  (JNIEnv *, jobject, jboolean, jint, jint, jFloat, jFloatArray, jint, jFloatArray, jint, jFloat, jFloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
