/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JOperation */

#ifndef _Included_com_wsr_cpu_JOperation
#define _Included_com_wsr_cpu_JOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD0ToD1
 * Signature: (FLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD0ToD1
  (JNIEnv *, jobject, jfloat, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD1ToD0
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD1ToD0
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD1ToD1
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD1ToD1
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD1ToD2
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD1ToD2
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD1ToD3
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD1ToD3
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD2ToD1
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD2ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD2ToD3
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD2ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD3ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD3ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD3ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD3ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD3ToD4
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD3ToD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD4ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD4ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD4ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD4ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    plusD4ToD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_plusD4ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD0ToD1
 * Signature: (FLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD0ToD1
  (JNIEnv *, jobject, jfloat, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD1ToD0
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD1ToD0
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD1ToD1
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD1ToD1
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD1ToD2
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD1ToD2
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD1ToD3
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD1ToD3
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD2ToD1
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD2ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD2ToD3
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD2ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD3ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD3ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD3ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD3ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD3ToD4
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD3ToD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD4ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD4ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD4ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD4ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    minusD4ToD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_minusD4ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD0ToD1
 * Signature: (FLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD0ToD1
  (JNIEnv *, jobject, jfloat, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD1ToD0
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD1ToD0
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD1ToD1
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD1ToD1
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD1ToD2
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD1ToD2
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD1ToD3
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD1ToD3
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD2ToD1
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD2ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD2ToD3
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD2ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD3ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD3ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD3ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD3ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD3ToD4
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD3ToD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD4ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD4ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD4ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD4ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    timesD4ToD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_timesD4ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD0ToD1
 * Signature: (FLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD0ToD1
  (JNIEnv *, jobject, jfloat, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD1ToD0
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD1ToD0
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD1ToD1
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD1ToD1
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD1ToD2
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD1ToD2
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD1ToD3
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD1ToD3
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD2ToD1
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD2ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD2ToD3
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD2ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD3ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD3ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD3ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD3ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD3ToD4
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;IIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD3ToD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD4ToD1
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD4ToD1
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD4ToD2
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD4ToD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JOperation
 * Method:    divD4ToD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOperation_divD4ToD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
