/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JTranspose */

#ifndef _Included_com_wsr_cpu_JTranspose
#define _Included_com_wsr_cpu_JTranspose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD2
 * Signature: ([FII[F)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD2
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD3
 * Signature: ([FIIIIII[F)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD3
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     com_wsr_cpu_JTranspose
 * Method:    transposeD4
 * Signature: ([FIIIIIIII[F)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JTranspose_transposeD4
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
