/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JOpenBLAS */

#ifndef _Included_com_wsr_cpu_JOpenBLAS
#define _Included_com_wsr_cpu_JOpenBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JOpenBLAS
 * Method:    sgemm
 * Signature: (ZZIIIFLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IFLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOpenBLAS_sgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jfloat, jobject, jint, jobject, jint, jfloat, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
