/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JMath */

#ifndef _Included_com_wsr_cpu_JMath
#define _Included_com_wsr_cpu_JMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JMath
 * Method:    exp
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMath_exp
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JMath
 * Method:    ln
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMath_ln
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wsr_cpu_JMath
 * Method:    pow
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMath_pow
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JMath
 * Method:    sqrt
 * Signature: (Ljava/nio/ByteBuffer;FLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JMath_sqrt
  (JNIEnv *, jobject, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
