/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JOpenBLAS */

#ifndef _Included_com_wsr_cpu_JOpenBLAS
#define _Included_com_wsr_cpu_JOpenBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JOpenBLAS
 * Method:    sgemm
 * Signature: (ZZIIIF[FI[FIF[FII)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JOpenBLAS_sgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jfloat, jfloatArray, jint, jfloatArray, jint, jfloat, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
