/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cpu_JCollection */

#ifndef _Included_com_wsr_cpu_JCollection
#define _Included_com_wsr_cpu_JCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    max
 * Signature: (Ljava/nio/ByteBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_com_wsr_cpu_JCollection_max
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    maxD1
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_maxD1
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    maxD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_maxD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    maxD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_maxD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    maxD4
 * Signature: (Ljava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_maxD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    min
 * Signature: (Ljava/nio/ByteBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_com_wsr_cpu_JCollection_min
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    minD1
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_minD1
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    minD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_minD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    minD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_minD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    minD4
 * Signature: (Ljava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_minD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    sum
 * Signature: (Ljava/nio/ByteBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_com_wsr_cpu_JCollection_sum
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    sumD1
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_sumD1
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    sumD2
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_sumD2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    sumD3
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_sumD3
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wsr_cpu_JCollection
 * Method:    sumD4
 * Signature: (Ljava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cpu_JCollection_sumD4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
