/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsr_cl_JCLBlast */

#ifndef _Included_com_wsr_cl_JCLBlast
#define _Included_com_wsr_cl_JCLBlast
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_init
  (JNIEnv *, jobject);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sdot
 * Signature: (I[FI[FI)F
 */
JNIEXPORT jfloat JNICALL Java_com_wsr_cl_JCLBlast_sdot
  (JNIEnv *, jobject, jint, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sscal
 * Signature: (IF[FI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sscal
  (JNIEnv *, jobject, jint, jfloat, jfloatArray, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    saxpy
 * Signature: (IF[FI[FI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_saxpy
  (JNIEnv *, jobject, jint, jfloat, jfloatArray, jint, jfloatArray, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sgemm
 * Signature: (ZZIIIF[FI[FIF[FI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sgemm
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jfloat, jfloatArray, jint, jfloatArray, jint, jfloat, jfloatArray, jint);

/*
 * Class:     com_wsr_cl_JCLBlast
 * Method:    sgemv
 * Signature: (ZIIF[FI[FIF[FI)V
 */
JNIEXPORT void JNICALL Java_com_wsr_cl_JCLBlast_sgemv
  (JNIEnv *, jobject, jboolean, jint, jint, jfloat, jfloatArray, jint, jfloatArray, jint, jfloat, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
