name: 'テストを実行'

on:
  workflow_dispatch:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 仮想ブランチにチェックアウト
        uses: actions/checkout@v4

      - name: Javaのセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: gradlewに権限を付与 (Unix)
        if: runner.os != 'Windows'
        run: chmod 777 ${{ github.workspace }}/gradlew

      - name: OpenBLASをインストール(Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libopenblas-dev
          echo "OPENBLAS_HOME=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: OpenBLASをインストール(Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p openblas
          curl -L -o "openblas.zip" "https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.31/OpenBLAS-0.3.31-x64.zip"
          tar -xf openblas.zip -C openblas
          echo "OPENBLAS_HOME=$((Get-Item .).FullName)\openblas\win64\lib" | Out-File -FilePath $env:GITHUB_ENV -Append
          
          tree

      - name: 探索
        if: runner.os == 'Windows'
        run: |
          cd D
          dir /s libmsvcprt.a
          dir /s libOLDNAMES.a

      - name: テストを実行
        run: |
          ./gradlew buffer:allTest --info
          ./gradlew io-type:allTest --info
          ./gradlew network:allTest --info
